### PR TITLE
Update 4_auto_ts_forecasting.ipynb

### PR DESCRIPTION
**Pull request by Kwentar**
fix wrong import

### CODE REVIEW

**Comment by Dreamlone** [comment]
Thank you very much for creating this PR and using our framework!
Please check if you have installed the correct version of the library. For fedot==0.3.0 all the imports that are specified in jupiter notebook only for that version.

The explanation: we regularly release versions of the FEDOT framework on PyPI. We try to maintain a consistent syntax for calling methods via the api. However, the internal functions (the one you are importing) may change from version to version. Right now, the latest version of fedot is 0.3.1. However, the notebook you changed belongs to the library version 0.3.0 (the library version is listed right under the heading). Notebooks for the new version 0.3.1 are not ready yet.

If you want to use the newest functionality, please install fedot from the master branch. All the necessary examples of how to use the updated methods can be found in the [cases](https://github.com/nccr-itmo/FEDOT/tree/master/cases) and [examples](https://github.com/nccr-itmo/FEDOT/tree/master/examples) folders.

So please, if you suggest these changes for version 0.3.1, create a folder called notebooks/version_03_1 and put this notebook in it. 

Later, we will update the rest of the notebooks and place them in this folder

**Comment by Kwentar** [comment]
I got, but problem is exist. Like regular user I did `pip install fedot` and go to tutorial and it has wrong import, so, maybe fix pip version with actual tutorials? And update it after docs & example for this version will be created.

**Comment by Dreamlone** [comment]
Yes, you are right. I've already create [hotfix PR](https://github.com/nccr-itmo/FEDOT/pull/334) to update versions in notebooks to make it more clear for users. Aftrer some time we will add a new folder "version_03_1" with updated examples for version fedot==0.3.1. I have created [the issue](https://github.com/nccr-itmo/FEDOT/issues/335) for that purpose.

For now, you can install version 0.3.0 instead of 0.3.1. There are a lot of examples how to use functionality of FEDOT framework

**Comment by J3FALL** [comment]
Just to make it more clear. Since we are adding new features rapidly, jupyter notebooks became outdated fast.
So we decided to update it after new major releases of FEDOT. In [notebooks](https://github.com/nccr-itmo/FEDOT/tree/master/notebooks) directory there are two folders according to v.0.2.1 and v.0.3.0.
Thus, it should work stable using the given versions. 

Maybe it is possible to improve our CI/CD to add new stage, like 'notebooks testing' that runs in PR-s. But the contributors have to fix it every time. 
@nicl-nno @BarabanovaIrina What do you think?

**Comment by BarabanovaIrina** [comment]
Thank you for sharing the problem. 
Since we use GitHub Actions for CI/CD, I've got only one [action](https://github.com/marketplace/actions/hybrid-interval) from Marketplace, which allows you to run notebooks with parameters. The workflow apparently simply runs defined notebooks which may help to avoid deployment of unstable notebooks versions.
Luckily, we are not alone. If this workflow will behave unexpectedly (there is now any rating for action, unfortunately) there is a [framework](https://github.com/ReviewNB/treon) for testing Jupiter notebooks so we could try to implement our own workflow with this solution. This is what I've got by quickly examining the problem.

**Pull request merged**
